
export const memberQuestions = [
  {
    id: "1",
    section: "Section 1 - Bio Data",
    page: 1,
    pageOrder: 1,
    displayType: "text",
    required: true,
    question: "First Name",
  },
  {
    id: "2",
    section: "Section 1 - Bio Data",
    page: 1,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "Last Name",
  },
  {
    id: "3",
    section: "Section 1 - Bio Data",
    page: 1,
    pageOrder: 3,
    displayType: "text",
    question: "Other Names or Alias",
  },
  {
    id: "4",
    section: "Section 1 - Bio Data",
    page: 2,
    pageOrder: 1,
    displayType: "date",
    required: true,
    question: "Date of Birth",
  },
  {
    id: "5",
    section: "Section 1 - Bio Data",
    page: 2,
    pageOrder: 2,
    displayType: "radio-single",
    required: true,
    question: "What is your Gender",
    options: [
        { label: 'Male', value: 'male' },
        { label: 'Female', value: 'female' },
      ]
  },
  {
    id: "6",
    section: "Section 1 - Bio Data",
    page: 2,
    pageOrder: 3,
    displayType: "radio-single",
    required: true,
    question: "Ever been a different Gender",
    options: [
        { label: 'Yes', value: 'yes' },
        { label: 'No', value: 'no' },
      ]
  },
  {
    id: "7",
    section: "Section 1 - Bio Data",
    page: 2,
    pageOrder: 4,
    displayType: "radio-single",
    question: "If Yes, select previous Gender",
    options: [
        { label: 'Male', value: 'male' },
        { label: 'Female', value: 'female' },
      ]
  },
  {
    id: "8",
    section: "Section 1 - Personal Details",
    page: 3,
    pageOrder: 1,
    displayType: "text-select",
    required: true,
    question: "Country of Origin",
  },
  {
    id: "9",
    section: "Section 1 - Personal Details",
    page: 3,
    pageOrder: 2,
    displayType: "text-select",
    required: true,
    question: "Country of Residence",
  },
  {
    id: "10",
    section: "Section 1 - Personal Details",
    page: 3,
    pageOrder: 3,
    displayType: "text-select",
    required: true,
    question: "City",
  },
  {
    id: "11",
    section: "Section 1 - Personal Details",
    page: 3,
    pageOrder: 4,
    displayType: "text-select",
    required: true,
    question: "Length of Residency",
    options: [
      "< 1 month",
      "1 month to 6 months",
      "6 months to 1 year",
      "1 year to 3 years",
      "> 3 years",
    ],
  },
  {
    id: "12",
    section: "Section 1 - Personal Details",
    page: 4,
    pageOrder: 1,
    displayType: "radio-single",
    required: true,
    question: "Are you very religious or more spiritual",
    options: ["Spritual", "Religious", "Both", "I do not care"],
  },
  {
    id: "13",
    section: "Section 1 - Personal Details",
    page: 4,
    pageOrder: 2,
    displayType: "select",
    required: true,
    question: "Select Religion",
  },
  {
    id: "14",
    section: "Section 1 - Personal Details",
    page: 4,
    pageOrder: 3,
    displayType: "yes-no",
    required: true,
    question: "Are you open to dating outside your religion",
  },
  {
    id: "15",
    section: "Section 1 - Personal Details",
    page: 5,
    pageOrder: 1,
    displayType: "select",
    required: true,
    question: "What's Your Racial Identity",
    options: [
      "American Indian/Alaska Native",
      "Asian",
      "Black or African American",
      "Native Hawaiian or other Pacific Islander",
      "Other - Not listed",
      "White/Caucasian",
      "Decline to Respond",
    ],
  },
  {
    id: "16",
    section: "Section 1 - Personal Details",
    page: 5,
    pageOrder: 2,
    displayType: "yes-no",
    required: true,
    question: "Are you open to dating outside your race",
  },
  {
    id: "17",
    section: "Section 1 - Personal Details",
    page: 5,
    pageOrder: 3,
    displayType: "select",
    required: true,
    question: "Select Genotype",
    options: ["AA", "AC", "AS", "SC", "SS"],
  },
  {
    id: "18",
    section: "Section 1 - Personal Details",
    page: 6,
    pageOrder: 1,
    displayType: "text-select",
    required: true,
    question: "Select Height",
  },
  {
    id: "19",
    section: "Section 1 - Personal Details",
    page: 6,
    pageOrder: 2,
    displayType: "text-select",
    required: true,
    question: "Estimated Weight",
  },
  {
    id: "20",
    section: "Section 1 - Personal Details",
    page: 6,
    pageOrder: 3,
    displayType: "radio-single",
    required: true,
    question: "What would you say is your body type",
    options: ["Average", "Skinny", "Curvy", "Athletic", "Thick", "Muscular"],
  },
  {
    id: "21",
    section: "Section 2 - History",
    page: 7,
    pageOrder: 1,
    displayType: "yes-no",
    required: true,
    question: "Ever been married",
  },
  {
    id: "22",
    section: "Section 2 - History",
    page: 7,
    pageOrder: 2,
    displayType: "radio-single",
    required: true,
    question:
      "If you selected Yes above, please choose which best applies below",
    options: ["Divorced", "Seperated", "Widowed"],
  },
  {
    id: "23",
    section: "Section 2 - History",
    page: 7,
    pageOrder: 3,
    displayType: "radio-single",
    required: true,
    question: "Do you have or want children",
    options: [
      "Want someday",
      "Don’t want",
      "Have and don’t want more",
      "Not sure yet",
      "Have and want more",
      "Open to kids",
    ],
  },
  {
    id: "24",
    section: "Section 2 - History",
    page: 7,
    pageOrder: 4,
    displayType: "text",
    required: true,
    question: "How many kids do you have",
  },
  {
    id: "25",
    section: "Section 2 - History",
    page: 8,
    pageOrder: 1,
    displayType: "radio-single",
    required: true,
    question: "How involved are you in your kid’s lives",
    options: [
      "I have no kids",
      "Mildly",
      "Very Involved",
      "Not Involved",
      "Involved",
    ],
  },
  {
    id: "26",
    section: "Section 2 - History",
    page: 8,
    pageOrder: 2,
    displayType: "yes-no",
    required: true,
    question: "Ever been arrested",
  },
  {
    id: "27",
    section: "Section 2 - History",
    page: 8,
    pageOrder: 3,
    displayType: "text",
    required: true,
    question: "Why were you arrested",
  },
  {
    id: "28",
    section: "Section 2 - History",
    page: 9,
    pageOrder: 1,
    displayType: "yes-no",
    required: true,
    question: "Ever been physically aggressive",
  },
  {
    id: "29",
    section: "Section 2 - History",
    page: 9,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "Kindly expatiate",
  },
  {
    id: "30",
    section: "Section 2 - History",
    page: 9,
    pageOrder: 3,
    displayType: "radio-single",
    required: true,
    question: "Who were you physically aggressive with",
    options: ["Same gender", "Children", "Opposite gender", "Animal"],
  },
  {
    id: "31",
    section: "Section 3 - Education",
    page: 10,
    pageOrder: 1,
    displayType: "select",
    required: true,
    question: "Education level",
    options: [
      "High School",
      "College",
      "Undergraduate",
      "Postgraduate",
      "Doctorate",
    ],
  },
  {
    id: "32",
    section: "Section 3 - Education",
    page: 10,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "Institution",
  },
  {
    id: "33",
    section: "Section 3 - Education",
    page: 10,
    pageOrder: 3,
    displayType: "select",
    required: true,
    question: "Graduation year",
  },
  {
    id: "34",
    section: "Section 4 - Work",
    page: 11,
    pageOrder: 1,
    displayType: "text",
    required: true,
    question: "What do you do",
  },
  {
    id: "35",
    section: "Section 4 - Work",
    page: 11,
    pageOrder: 2,
    displayType: "text-select",
    required: true,
    question: "Work Industry",
  },
  {
    id: "36",
    section: "Section 4 - Work",
    page: 11,
    pageOrder: 3,
    displayType: "text",
    question: "What’s your LinkedIn",
  },
  {
    id: "37",
    section: "Section 4 - Work",
    page: 12,
    pageOrder: 1,
    displayType: "select",
    required: true,
    question: "What’s your estimated networth",
  },
  {
    id: "38",
    section: "Section 4 - Work",
    page: 12,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "Enter networth",
  },
  {
    id: "39",
    section: "Section 4 - Work",
    page: 12,
    pageOrder: 3,
    displayType: "yes-no",
    required: true,
    question: "Can you provide up to 2 professional referees",
  },
  {
    id: "40",
    section: "Section 4 - Work",
    page: 13,
    pageOrder: 1,
    displayType: "text",
    required: true,
    question: "Full Name of First Referee",
  },
  {
    id: "41",
    section: "Section 4 - Work",
    page: 13,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "How did you meet",
  },
  {
    id: "42",
    section: "Section 4 - Work",
    page: 13,
    pageOrder: 3,
    displayType: "complex",
    required: true,
    question: "How long have you known each other",
    options: ["Month", "Year"],
  },
  {
    id: "43",
    section: "Section 4 - Work",
    page: 13,
    pageOrder: 4,
    displayType: "text",
    required: true,
    question: "Referee’s LinkedIn",
  },
  {
    id: "44",
    section: "Section 4 - Work",
    page: 14,
    pageOrder: 1,
    displayType: "complex",
    required: true,
    question: "Reference Phone",
  },
  {
    id: "45",
    section: "Section 4 - Work",
    page: 14,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "Email",
  },
  {
    id: "46",
    section: "Section 4 - Work",
    page: 15,
    pageOrder: 1,
    displayType: "text",
    required: true,
    question: "Full Name of First Referee",
  },
  {
    id: "47",
    section: "Section 4 - Work",
    page: 15,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "How did you meet",
  },
  {
    id: "48",
    section: "Section 4 - Work",
    page: 15,
    pageOrder: 3,
    displayType: "complex",
    required: true,
    question: "How long have you known each other",
    options: ["Month", "Year"],
  },
  {
    id: "49",
    section: "Section 4 - Work",
    page: 15,
    pageOrder: 4,
    displayType: "text",
    required: true,
    question: "Referee’s LinkedIn",
  },
  {
    id: "50",
    section: "Section 4 - Work",
    page: 16,
    pageOrder: 1,
    displayType: "complex",
    required: true,
    question: "Reference Phone",
  },
  {
    id: "51",
    section: "Section 4 - Work",
    page: 16,
    pageOrder: 2,
    displayType: "text",
    required: true,
    question: "Email",
  },
  {
    id: "52",
    section: "Section 5 - Additional Documents",
    page: 17,
    pageOrder: 1,
    displayType: "file",
    question: "Upload your resume",
  },
  {
    id: "53",
    section: "Section 5 - Additional Documents",
    page: 17,
    pageOrder: 2,
    displayType: "file",
    question: "Upload bank statement",
  },
  {
    id: "54",
    section: "Section 5 - Additional Documents",
    page: 17,
    pageOrder: 3,
    displayType: "yes-no",
    required: true,
    question: "Have a criminal record",
  },
  {
    id: "55",
    section: "Section 5 - Additional Documents",
    page: 17,
    pageOrder: 4,
    displayType: "text",
    question: "Kindly expatiate",
  },
];